#################################################################
# Config for A2A Agent, that can embed a MCP agent
#################################################################

#################################################################
# General parameters
#################################################################
agent_name="Basic_Agent"
agent_host="127.0.0.1"
agent_http_port="8080"

# Future use. Websocket is not supported
agent_ws_port="8081"

#################################################################
# Future use : It would make sense to have a discovery service
# so that planner agent can dynamically discover agents to
# connect to
#################################################################
agent_discovery_url="http://127.0.0.1:4000"

#################################################################
# Agent Evaluation Service
#################################################################
agent_evaluation_service_url="http://127.0.0.1:7000"

#################################################################
# Agent Memory Service
#################################################################
agent_memory_service_url="http://127.0.0.1:5000"


#################################################################
# Purpose and high level skills
# The agent will use the A2A protocol for his interactions
#################################################################
agent_system_prompt="You are a helpful assistant that answers user requests. You can execute search in wikipedia content. You are a specialist of customer data access, as well as weather forecast. When you are passed some context information, you use them in order to fulfill user query."
agent_skill_id="generic_request"
agent_skill_name="All search inside wikipedia, and requests about Weather and Customer Data Access"
agent_skill_description="Helps with search inside wikipedia, customer data access, weather forecast, and other generic requests."
agent_version="1.0.0"
agent_description="An agent that can process requests related to seach inside wikipedia, weather, customer information."
agent_doc_url="/docs"
agent_tags=["find weather","details about customer","general","wikipedia search"]
agent_examples=["What is the weather like in Boston?","What is address of customer 1234","Tell me about rust"]

#################################################################
# Define her the url of openai compatible endpoint 
# as well as the model to use
#################################################################
# These set of parameters declares the LLM that the agent will connect to
#agent_model_id="gemini-2.0-flash"
#agent_llm_url="https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
agent_model_id="qwen/qwen3-32b"
#agent_model_id="openai/gpt-oss-20b"
#agent_model_id="deepseek-r1-distill-llama-70b"
#agent_model_id="meta-llama/llama-4-scout-17b-16e-instruct"
agent_llm_url="https://api.groq.com/openai/v1/chat/completions"

#################################################################
# You can say the agent to include a MCP runtime agent
# you just define the configuration file to use
#################################################################
agent_mcp_config_path="documentation/demo_workflow_management/mcp_runtime_config.toml"

