[package]
name = "hierarchical_planner"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
async-trait =  {workspace=true}
serde =  {workspace=true}
serde_json =  {workspace=true}
tokio =  {workspace=true}
agent_core = {workspace=true}
