[package]
name = "workflow_management"
version = "0.1.0"
edition = "2021"

[dependencies]
a2a-rs= { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
agent_protocol_backbone = { workspace = true }


[lib]
name = "workflow_management"
path = "src/lib.rs"
