[package]
name = "workflow_management"
version = "0.1.0"
edition = "2021"

[dependencies]
serde={ workspace = true }
serde_json={ workspace = true }
anyhow={ workspace = true }
clap = "4"
toml = "0.9"
thiserror = "2.0"
tokio = { workspace = true }


[[bin]]
name = "workflow_management"
path = "bin/workflow_orchestrator_launch.rs"