agent_mcp_role_tool = "tool"
agent_mcp_role_assistant = "assistant"
agent_mcp_tool_choice_auto = "auto"
agent_mcp_finish_reason_tool_calls = "tool_calls"
agent_mcp_finish_reason_stop = "stop"
agent_mcp_max_loops = 5
agent_mcp_server_url="http://localhost:8000/sse"
agent_mcp_server_api_key="<YOUR_API_KEY>"
agent_mcp_model_id="qwen/qwen3-32b"
agent_mcp_system_message= "You are a helpful assistant that answers user requests. You can use one or more tools. When you receive a message with a role called \"tool\", you must use the response from tools in order to build a final answer."
agent_mcp_endpoint="http://localhost:3000/"
