agent_planner_name="planner"
agent_planner_system_prompt="You are a helpful planner agent"
agent_planner_model_id="qwen/qwen3-32b"
agent_planner_discovery_url="http://127.0.0.1:4000/"
# put a nested Struct with name and url
agent_planner_agents_url = [ "http://127.0.0.1:8081/", "http://127.0.0.1:8082/", "http://127.0.0.1:8083/" ]
