#################################################################
# Config for A2A Agent, that can embed a MCP agent
#################################################################

#################################################################
# General parameters
#################################################################
agent_name="Weather Information Agent"
agent_host="127.0.0.1"
agent_http_port="8120"

# Future use. Websocket is not supported
agent_ws_port="8121"

#################################################################
# Future use : It would make sense to have a discovery service
# so that planner agent can dynamically discover agents to
# connect to
#################################################################
agent_discovery_url="http://127.0.0.1:4000"


#################################################################
# Purpose and high level skills
# The agent will use the A2A protocol for his interactions
#################################################################
agent_system_prompt="You are a specialized agent providing accurate and up-to-date weather information. You can answer queries about current weather conditions, forecasts, and specific meteorological data for any location worldwide."
agent_skill_id="weather_information_retrieval"
agent_skill_name="Current Weather and Forecasts"
agent_skill_description="Provides real-time weather conditions, short-term and long-term forecasts, temperature, humidity, wind speed, precipitation, and other meteorological data for specified locations."
agent_version="1.0.0"
agent_description="An agent dedicated to fetching and delivering comprehensive weather information for any requested location."
agent_doc_url="/docs"
agent_tags=["weather","forecast","temperature","humidity","precipitation","climate","meteorology"]
agent_examples=[
    "What's the weather like in London right now?",
    "What is the 5-day forecast for New York City?",
    "Will it rain in Tokyo tomorrow?",
    "What's the wind speed in Chicago?",
    "Tell me the current temperature in Sydney."
]

#################################################################
# Define her the url of openai compatible endpoint
# as well as the model to use
#################################################################
# These set of parameters declares the LLM that the agent will connect to
agent_model_id="gemini-2.0-flash"
agent_llm_url="https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"

#################################################################
# You can say the agent to include a MCP runtime agent
# you just define the configuration file to use
# MCP connected to weather forecast is mandatory for this agent
#################################################################
# agent_mcp_config_path="configuration/agent_mcp_weather_config.toml"
