#################################################################
# Config for A2A Agent, that can embed a MCP agent
#################################################################

#################################################################
# General parameters
#################################################################
agent_name="Humor Bot"
agent_host="127.0.0.1"
agent_http_port="8080"

# Future use. Websocket is not supported
agent_ws_port="8081"

#################################################################
# Future use : It would make sense to have a discovery service
# so that planner agent can dynamically discover agents to
# connect to
#################################################################
agent_discovery_url="http://127.0.0.1:4000"


#################################################################
# Purpose and high level skills
# The agent will use the A2A protocol for his interactions
#################################################################
agent_system_prompt="You are a friendly and versatile joke-telling agent. Your goal is to bring laughter to your audience, adapting your humor style and content to suit children, middle-aged individuals, and older people. You can tell knock-knock jokes, puns, observational humor, and general funny stories."
agent_skill_id="joke_telling"
agent_skill_name="Humor and Entertainment"
agent_skill_description="Delivers jokes suitable for a wide demographic, from child-friendly humor to more nuanced jokes for adults, ensuring appropriate content and style for the specified audience."
agent_version="1.0.0"
agent_description="An agent specialized in telling jokes, capable of tailoring humor for children, middle-aged individuals, and older people."
agent_doc_url="/docs"
agent_tags=["jokes","humor","entertainment","comedy","children","adults","puns","knock-knock"]
agent_examples=[
    "Tell me a joke for a 5-year-old.",
    "Can you tell a funny story suitable for adults?",
    "Give me a pun.",
    "Tell a joke that an older person would appreciate.",
    "Make me laugh with a clean joke."
]

#################################################################
# Define her the url of openai compatible endpoint
# as well as the model to use
#################################################################
# These set of parameters declares the LLM that the agent will connect to
agent_model_id="gemini-2.0-flash"
agent_llm_url="https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"

#################################################################
# You can say the agent to include a MCP runtime agent
# you just define the configuration file to use
#################################################################
#agent_mcp_config_path="configuration/agent_mcp_joke_config.toml"
